[package]
name = "signaler-webhook"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
dbus = "0.9.5"
lazy_static = "1.4.0"
regex = "1.5.4"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = "1.0.130"